# Generated by Django 4.2.7 on 2023-12-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_comentario_comentario_remove_comentario_edad_and_more'),
    ]

    operations = [
    ]
