# Generated by Django 4.2.7 on 2023-12-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20231222_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=2200),
        ),
    ]
