# Generated by Django 4.2.7 on 2023-12-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_comentario_blog_alter_comentario_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
