# Generated by Django 4.2.7 on 2023-12-24 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/blogs'),
        ),
    ]
