# Generated by Django 4.2.7 on 2023-12-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_blog_fecha_blog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
